# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
gem "jekyll-archives"
gem "jekyll-diagrams"
gem "jekyll-email-protect"
gem "jekyll-feed"
gem "jekyll-github-metadata"
gem "jekyll-imagemagick"
gem "jekyll-paginate-v2"
gem "jekyll-scholar"
gem "jekyll-sitemap"
gem "jekyll-target-blank"
gem "jekyll-twitter-plugin"
gem "jemoji"
gem "unicode_utils"
gem "webrick"
gem "htmlcompressor"
gem "htmlbeautifier" 